[tool.poetry]
name = "price-pulse"
version = "0.1.0"
description = "Giving you the heartbeat of pricing across sites ï¿½ï¿½ğŸ”"
authors = ["el-tegy <elisee.tegue@groupe-esigelec.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[tool.poetry.group.dev.dependencies]
pylint = "^3.0.1"
black = "^23.10.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
